<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>10.0.1-dev.2</Version>
    <Authors>DevDogs</Authors>
    <Company>OneWeb Co., Ltd.</Company>
    <Description>Shared libraries</Description>
    <Copyright>Copyright 2025 @ OneWeb Co., Ltd.</Copyright>
    <PackageProjectUrl>https://www.oneweb.co.th</PackageProjectUrl>
    <PackageIcon>logo.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://gitlab.com/dmnsn/libraries/core</RepositoryUrl>
    <ApplicationIcon>dimension.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="dimension.ico" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.1" />
  </ItemGroup>
</Project>